package me.udayraj.vmmanager.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import me.udayraj.vmmanager.model.SshLogin;
import me.udayraj.vmmanager.model.VmStatus;

import java.time.LocalDateTime;
import java.util.UUID;

public record VMInformation(
        UUID id, // This can be null for new VMs, generated by DB

        @NotBlank(message = "{validation.ipAddress.notBlank}")
        String ipAddress, // Mandatory

        @Min(value = 1, message = "{validation.portNumber.min}")
        int portNumber,

        @NotBlank(message = "{validation.username.notBlank}")
        String username, // Mandatory

        String password, // Mandatory

        @NotBlank(message = "{validation.osName.notBlank}")
        String osName, // Mandatory

        @NotBlank(message = "{validation.hostName.notBlank}")
        String hostName, // Mandatory

        @NotBlank(message = "{validation.cpuCores.notBlank}")
        String cpuCores, // Mandatory

        @NotBlank(message = "{validation.rootPartitionSize.notBlank}")
        String rootPartitionSize, // Mandatory

        @NotBlank(message = "{validation.totalRamSize.notBlank}")
        String totalRamSize, // Mandatory

        @NotBlank(message = "{validation.macAddress.notBlank}")
        String macAddress, // Mandatory

        // Fields for business context and auditing
        @NotBlank(message = "{validation.category.notBlank}")
        String category, // Mandatory

        String purpose,

        @NotBlank(message = "{validation.ownerName.notBlank}")
        String ownerName,

        boolean isLinux, // Mandatory

        VmStatus status, 
        LocalDateTime createdDate,
        LocalDateTime lastUpdatedDate
        ) {
    public static VMInformation createWithSshDetails(
            SshLogin login,
            String osName,
            String hostName,
            String cpuCores,
            String rootPartitionSize,
            String totalRamSize,
            String macAddress
    ) {
        return new VMInformation(
                null, // ID is generated by the database upon saving
                login.ipAddress(),
                login.portNumber(),
                login.username(),
                login.password(),
                osName,
                hostName,
                cpuCores,
                rootPartitionSize,
                totalRamSize,
                macAddress,
                null, // Category
                null, // Purpose
                null, // Owner Name
                osName != null && !osName.toLowerCase().contains("windows"), // is it Linux?
                VmStatus.ACTIVE, // Default status for a newly discovered VM
                null, // Created Date
                null  // Last Updated Date
        );
    }
}
